services:
  sherpa-dns:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../sherpa-dns.yaml:/config/sherpa-dns.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Set these in .env file in the root directory
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    # restart: unless-stopped
    ports:
      - "8080:8080"
